name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .brachyura
            ~/.brachyura
          key: ${{ runner.os }}-brachyura-${{ hashFiles('**/Buildscript.java') }}
          restore-keys: ${{ runner.os }}-brachyura
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: java -jar brachyura-bootstrap-0.jar build
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
